workflows:
  hooks:
    environment:
      groups:
        - secure
    triggering:
      events:
        - push
        - pull_request
        - pull_request_labeled      #GitHub only
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: false
    scripts:
      - printenv
